# yaml file for gitHub CI for
# Chris' Assignment 2

name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest pytest-cov loguru

    - name: Analysing the code with pylint
      if: always()
      run: |
        pylint `ls -R|grep .py$|xargs`

    - name: Run tests
      if: always()
      run: |
        pytest ./

    - name: Run test coverage
      if: always()
      run: |
        pytest --cov=main --cov=users --cov=user_status --cov=menu --cov-fail-under=100 ./
