name: CodeChecks

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # core packages needed for testing
        pip install pylint pytest pytest-cov
        # extra requirements for this project
        pip install -r requirements.txt

    - name: Analysing the code with pylint
      if: always()
      run: |
        pylint `ls -R|grep .py$|xargs`

    - name: Run tests
      if: always()
      run: |
        pytest ./

    - name: Run test coverage
      if: always()
      run: |
        pytest --cov --cov-fail-under=100 ./

